### ISSUE TITLE
 Invalid value for environment variable "RCLONE_VERSION"?

### ISSUE THREAD

**Issue by Brian78912** [tynor88/docker-rclone#19]
Hi great solution, i use it to backup zoneminder pictures to the cloud :)

But sometime ago i started to get strange erros, and no data i synchronized 

Error:  Invalid value for environment variable "RCLONE_VERSION": strconv.ParseBool: parsing "current": invalid syntax

I have tryied to delte container and set it up again. 

Hope sombody can help :)

Picture form portainer.io 
![image](https://user-images.githubusercontent.com/48408624/85925295-b08fad80-b897-11ea-947e-8d8b00214023.png)

**Comment by SlothCroissant** [comment]
+1 - I forked the project in an attempt to submit a PR to fix it, but by simply forking it and making no changes, the subsequent docker hub build succeeded and my same exact config now works. I think @tynor88 may just need to trigger a build or something.

ref: https://hub.docker.com/r/slothcroissant/rclone

**Comment by tynor88** [comment]
Hi @Brian78912  and @SlothCroissant 
I just triggered a build. Will be done in 10 minutes. Let me know if it works.

**Comment by Brian78912** [comment]
Hi @SlothCroissant and @tynor88 thanks, i have just run a test it's unfortunately not resolved in my case :(
Removed the container recreated it with same .rclone.config, in config folder.

**Comment by SlothCroissant** [comment]
Be sure to remove the container with `docker rm -fv <name>` so it purges the images and volumes and Docker has to re-pull them. 

Does this happen on both images? @tynor88’s and my test fork?

**Comment by Brian78912** [comment]
> Be sure to remove the container with `docker rm -fv <name>` so it purges the images and volumes and Docker has to re-pull them.
> 
> Does this happen on both images? @tynor88’s and my test fork?

Done, same problem :(

**Comment by Brian78912** [comment]
@SlothCroissant  your build works, thanks :) at the moment i cannot get tynors to work, same error.

**Comment by dsluijk** [comment]
I had the same issue before, but I did end up solving it like this:

```yaml
rclone:
    image: tynor88/rclone
    environment:
      SYNC_DESTINATION: "ftp"
      SYNC_COMMAND: "env RCLONE_VERSION=true rclone copy /data ftp:/**path_to_destination** --config /config/rclone.conf"
    volumes:
      - ./:/config
      - /data:/data:ro
```

Not the prettiest, but it gets the job done.

**Comment by Brian78912** [comment]
@dsluijk  Thanks, this works great thank you :)

**Comment by timdonovanuk** [comment]
Still an issue. I don't get how a fork of this can have 1M+ pulls from dockerhub but not actually work?! 

https://hub.docker.com/r/that1guy/docker-rclone

**Comment by tynor88** [comment]
Which fork?

**Comment by smartnet-club** [comment]
RCLONE_* is a predefined prefix of rclone options.
just rename env variable. for ex MY_RCLONE_VERSION
